// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SokoolTools.VsTools
{
    static class Vsix
    {
        public const string Id = "7a2977ea-8c89-4d9f-bbb6-96b2040e23b6";
        public const string Name = "VSTools";
        public const string Description = @"Visual Studio Tools Extension Copyright © 2012-2019 SokoolTools.";
        public const string Language = "en-US";
        public const string Version = "3.0.1.61";
        public const string Author = "SokoolTools";
        public const string Tags = "";
    }
}
