//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SokoolTools.VsTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SokoolTools.VsTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Date: {0}.
        /// </summary>
        internal static string About_ModDate {
            get {
                return ResourceManager.GetString("About_ModDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;ABOUT&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: &apos;Lucida Sans&apos;, &apos;Lucida Sans Regular&apos;, &apos;Lucida Grande&apos;, &apos;Lucida Sans Unicode&apos;, Geneva, Verdana, sans-serif;
        ///            font-size: 0.75em;
        ///            width: 98%;
        ///        }
        ///
        ///        h3 {
        ///            margin-top: .25em;
        ///        }
        ///
        ///        hr {
        ///            margin-right: 1em;
        ///        }
        ///
        ///        table {
        ///            width: 98%
        ///        }
        ///
        ///        tr {
        ///            display [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;SYSTEM INFO&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: &apos;Lucida Sans&apos;, &apos;Lucida Sans Regular&apos;, &apos;Lucida Grande&apos;, &apos;Lucida Sans Unicode&apos;, &apos;Geneva&apos;, &apos;Verdana&apos;, sans-serif;
        ///            font-size: 0.75em;
        ///        }
        ///
        ///        h3 {
        ///            margin-top: 0.25em;
        ///        }
        ///
        ///        hr {
        ///            margin-right: 1em;
        ///        }
        ///
        ///        .p1 {
        ///            font-weight: 800;
        ///            background-color: lightgray;
        ///            m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command only works on an active solution... 
        ///Please load or create a solution then try again..
        /// </summary>
        internal static string CommandOnlyWorksOnActiveSolution {
            get {
                return ResourceManager.GetString("CommandOnlyWorksOnActiveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Text Changes.
        /// </summary>
        internal static string DynamicTextBaseText {
            get {
                return ResourceManager.GetString("DynamicTextBaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Clicked {1} times).
        /// </summary>
        internal static string DynamicTextFormat {
            get {
                return ResourceManager.GetString("DynamicTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exp {
            get {
                object obj = ResourceManager.GetObject("Exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to collapse. You must have an open solution..
        /// </summary>
        internal static string NothingToCollapse {
            get {
                return ResourceManager.GetString("NothingToCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to &apos;Optimize Usings&apos; on the entire project?.
        /// </summary>
        internal static string OptimizeEntireProject {
            get {
                return ResourceManager.GetString("OptimizeEntireProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to &apos;Optimize Usings&apos; on the entire solution?.
        /// </summary>
        internal static string OptimizeEntireSolution {
            get {
                return ResourceManager.GetString("OptimizeEntireSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executable file you specified does not exist..
        /// </summary>
        internal static string OptionsDialog_FileDoesNotExist {
            get {
                return ResourceManager.GetString("OptionsDialog_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the external tool executable file:.
        /// </summary>
        internal static string OptionsDialog_SelectFile {
            get {
                return ResourceManager.GetString("OptionsDialog_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one project or project item must be selected for this command to work..
        /// </summary>
        internal static string ProjectMustBeSelected {
            get {
                return ResourceManager.GetString("ProjectMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RegexHelp {
            get {
                object obj = ResourceManager.GetObject("RegexHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
